session_name: experiments
shell_command_before: "export RUST_LOG=info; clear;"
windows:
  - window_name: code
    focus: true
    start-directory: ./
    panes:
      - shell_command:
        - helix
  - window_name: agent
    start-directory: ./
    panes:
      - shell_command:
        - claude
  - window_name: srv
    start-directory: ./
    panes:
      - shell_command:
        - exa --long
  - window_name: notes
    panes:
      - shell_command:
        - emacs -nw notes.org
